---
title: "Scoring matrix"
output: html_document
---

This document will implement the filling of the scoring matrix using the
Smith-Waterman algorithm with affine gap penalty.

We first initialise the inputs (random, these will come from the user or set by default):

```{r}
sequence1_char = "AAGCTT"
sequence2_char = "AGCTAT"
sequence1 = as.list(strsplit(sequence1_char, "")[[1]])
sequence2 = as.list(strsplit(sequence2_char, "")[[1]])
gap_open_penalty = 12
gap_extend_penalty = 3
subst_matrix = matrix(c(
   c(5, -4, -4, -4),
   c(-4, 5, -4, -4),
   c(-4, -4, 5, -4),
   c(-4, -4, -4, 5)), 4, 4)
rownames(subst_matrix) <- c("A","T","G","C")
colnames(subst_matrix) <- c("A","T","G","C")
```
Now we initialise the matrix:

```{r}
rows = length(sequence1) + 1
columns = length(sequence2) + 1
S = matrix(0, rows, columns) # scoring matrix
V = matrix(0, rows, columns)
H = matrix(0, rows, columns)

for (i in 2:rows) {
  for (j in 2:columns) {
    V[i,j] <- max(S[i-1,j]-gap_open_penalty,
                  V[i-1,j]-gap_extend_penalty)
    H[i,j] <- max(S[i,j-1]-gap_open_penalty,
                  H[i,j-1]-gap_extend_penalty)
    S[i,j] <- max(0, S[i-1,j-1] + subst_matrix[sequence1[[i-1]],sequence2[[j-1]]],
                  V[i,j],
                  H[i,j])
  }
}
```
