---
title: "Dynamic Programming_Traceback"
output: html_document
---

```{r setup, include=FALSE}
rm(list = ls())
```

```{r}
# Temporary Input Variables

scoring_matrix <- matrix(1:16, nrow = 4, ncol = 4)
scoring_matrix[1,] <- 0
scoring_matrix[,1] <- 0
#scoring_matrix <- t(scoring_matrix)
seq_1 <- c('a','b','c')
seq_2 <- c('d','e','f')

string_1 <- c()
string_2 <- c()

print(scoring_matrix)
```
```{r}
# find maximum value in scoring matrix and allocate as score
score <- max(scoring_matrix)
start_position <- which(scoring_matrix == score, arr.ind = TRUE)
print(start_position)
string_1 <- append(string_1, seq_1[start_position[1]-1])
string_2 <- append(string_2, seq_2[start_position[2]-1])
print(string_1)
print(string_2)
```
```{r}
# move to next position in scoring matrix
position <- start_position

while (scoring_matrix[position] != 0) {

  # Create vector of next possible steps
  vertical <- scoring_matrix[position[1] -1, position[2]]
  horizontal <- scoring_matrix[position[1], position[2] -1]
  diagonal <- scoring_matrix[position[1] -1, position[2] -1]

  step_vec <- c(vertical, horizontal, diagonal)
  step <- max(step_vec)
  
  #create movement vector
  jump <- c(0,0)
  
  if(step == diagonal) {
    jump <- c(-1, -1)
    position <- position + jump
    string_1 <- append(string_1, seq_1[position[1]-1])
    string_2 <- append(string_2, seq_2[position[2]-1])
    
  } else if (step == horizontal) {
    jump <- c(0, -1)
    position <- position + jump
    string_1 <- append(string_1, '_')
    string_2 <- append(string_2, seq_2[position[2]-1])
    
  } else {
    jump <- c(-1, 0)
    position <- position + jump
    string_1 <- append(string_1, seq_1[position[1]-1])
    string_2 <- append(string_2, '_')
  }
  
  # new position vector is old + movement
  #position <- position + jump
  
}

print(rev(string_1))
print(rev(string_2))
```
```{r}
seq_x <- c('a','b','c')
str_x <- c()
str_x <- append(str_x, seq_x[1])
print(str_x)
str_x <- append(str_x, seq_x[2])
print(str_x)
```